OperationManagementSystem/apps/deploy/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'deploy'

urlpatterns = [
    url(r'^apply_manage/$', views.DeployApplyListView.as_view(), name='apply_manage'),
    url(r'^apply_delete/(?P<apply_id>[0-9]+)/$', views.deploy_apply_delete, name='apply_delete'),
    url(r'^apply_create/$', views.DeployApplyCreateView.as_view(), name='apply_create'),
    url(r'^apply_update/(?P<pk>[0-9]+)/$', views.DeployApplyUpdateView.as_view(), name='apply_update'),
]

OperationManagementSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from OperationManagementSystem.apps.dashboard.views import alarm_charts

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^system/', include('OperationManagementSystem.apps.system.urls')),
    url(r'^config/', include('OperationManagementSystem.apps.config.urls')),
    url(r'^operation/', include('OperationManagementSystem.apps.operation.urls')),
    url(r'^alarm/', include('OperationManagementSystem.apps.alarm.urls')),
    url(r'^dashboard/', include('OperationManagementSystem.apps.dashboard.urls')),
    url(r'^deploy/', include('OperationManagementSystem.apps.deploy.urls')),
    url(r'^oms_config_api/', include('OperationManagementSystem.apps.oms_config_api.urls')),
    url(r'^mychannels/', include('OperationManagementSystem.apps.mychannels.urls')),
    url(r'^jenkins/', include('OperationManagementSystem.apps.jenkins.urls')),
    url(r'^$', alarm_charts, name='index'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

OperationManagementSystem/apps/deploy/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from OperationManagementSystem.apps.system.models import Application


class DeployApply(models.Model):
    WAITFORCOMMIT = 'WC'
    WAITFORDEPLOY = 'WD'
    CANCELED = 'C'
    DEPLOYED = 'D'
    DEVMANAGERAPPROVAL = 'DA'
    OPERMANAGERAPPROVAL = 'OA'
    ENGINEERAPPROVAL = 'EA'
    TESTMANAGERAPPROVAL = 'TA'
    TECHNICALDIRECTORYAPPROVAL = 'TDA'
    status_CHOICES = (
        (WAITFORCOMMIT, '待提交'),
        (WAITFORDEPLOY, '待发布'),
        (CANCELED, '已取消'),
        (DEPLOYED, '已发布'),
        (DEVMANAGERAPPROVAL, '研发经理审批中'),
        (OPERMANAGERAPPROVAL, '运维经理审批中'),
        (ENGINEERAPPROVAL, '运维工程师审批中'),
        (TESTMANAGERAPPROVAL, '测试经理审批中'),
        (TECHNICALDIRECTORYAPPROVAL, '技术总监审批中'),
    )
    apply_project = models.CharField("申请编号", max_length=50)
    status = models.CharField(
        "申请状态",
        max_length=3,
        choices=status_CHOICES,
        default=WAITFORCOMMIT,
    )
    apply_user = models.CharField("申请人", max_length=20, null=True, blank=True)
    apply_time = models.DateTimeField("申请时间", auto_now_add=True)
    deploy_user = models.CharField("发布人", max_length=20, null=True, blank=True)
    deploy_time = models.DateTimeField("实际发布时间", null=True, blank=True)
    conf_amend_explain = models.TextField("配置修改说明", null=True, blank=True)
    remark_explain = models.TextField("备注事项", null=True, blank=True)
    verify_result = models.CharField(
        max_length=1,
        choices=(('Y', '审核通过'), ('N', '审核不通过')),
        null=True,
        blank=True,
        verbose_name="审核结果"
    )
    wish_deploy_time = models.DateField("期望发布日期", null=True, blank=True)

    class Meta:
        verbose_name = u'发布申请列表'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.apply_name


class DeployApplyOperateLog(models.Model):
    deploy_apply = models.ForeignKey(DeployApply, on_delete=models.CASCADE, verbose_name=u'所属申请发布单')
    type = models.CharField(max_length=10, verbose_name=u'发布应用代码类型')
    operator_name = models.CharField(max_length=30, verbose_name=u'操作人')
    operation_time = models.DateTimeField(auto_now_add=True, verbose_name=u'操作时间')

    class Meta:
        verbose_name = u'发布申请审批日志'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.operator_name

OperationManagementSystem/apps/deploy/forms.py
from django.forms.models import inlineformset_factory
from django.forms import ModelForm
from OperationManagementSystem.apps.deploy.models import DeployApply
from OperationManagementSystem.apps.operation.models import DeployItem


class DeployApplyForm(ModelForm):
    class Meta:
        model = DeployApply
        fields = ['apply_project', 'apply_user', 'conf_amend_explain', 'remark_explain']


DeployItemFormSet = inlineformset_factory(DeployApply, DeployItem, fields=('deploy_order_by', 'jenkins_version',
                                                                           'deploy_application', 'type'), extra=1,
                                          can_delete=True)

OperationManagementSystem/apps/deploy/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse
from OperationManagementSystem.apps.deploy.models import DeployApply
from OperationManagementSystem.apps.deploy.forms import DeployApplyForm, DeployItemFormSet
from OperationManagementSystem.apps.operation.models import DeployECS
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, HttpResponse
from datetime import datetime
import json

app_name = 'deploy'


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class DeployApplyListView(generic.ListView):
    model = DeployApply
    template_name = 'deploy/apply_manage.html'
    context_object_name = 'apply_manage'

    def get_queryset(self):
        apply_manage = DeployApply.objects.order_by('-apply_time')
        return apply_manage


@login_required(login_url='/login/')
def deploy_apply_delete(request, apply_id):
    deploy_apply = DeployApply.objects.get(pk=apply_id)
    deploy_apply.delete()
    return HttpResponse(json.dumps({'success': True}), content_type='application/json')


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class DeployApplyCreateView(generic.CreateView):
    template_name = 'deploy/apply_create.html'
    model = DeployApply
    form_class = DeployApplyForm
    success_url = '/deploy/apply_manage/'

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        deploy_apply_form = self.get_form(form_class)
        deploy_item_formset = DeployItemFormSet()
        return self.render_to_response(
            self.get_context_data(deploy_apply_form=deploy_apply_form,
                                  deploy_item_formset=deploy_item_formset))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        deploy_apply_form = self.get_form(form_class)
        if request.POST['wish_deploy_time']:
            wish_deploy_date = datetime.strptime(str(request.POST['wish_deploy_time']), "%d/%m/%Y").strftime("%Y-%m-%d")
            deploy_apply_form.instance.wish_deploy_time = wish_deploy_date
        deploy_apply_form.instance.apply_user = request.user.username
        deploy_item_formset = DeployItemFormSet(self.request.POST)
        if deploy_item_formset:
            if (deploy_apply_form.is_valid()
                    and deploy_item_formset.is_valid()):
                return self.form_valid(request, deploy_apply_form, deploy_item_formset)
            else:
                return self.form_invalid(deploy_apply_form, deploy_item_formset)
        else:
            if deploy_apply_form.is_valid():
                return self.form_valid(request, deploy_apply_form, '')

    def form_valid(self, request, deploy_apply_form, deploy_item_formset):
        self.object = deploy_apply_form.save()
        deploy_item_formset.instance = self.object
        deploy_item_formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, deploy_apply_form, deploy_item_formset):
        return self.render_to_response(
            self.get_context_data(deploy_apply_form=deploy_apply_form,
                                  deploy_item_formset=deploy_item_formset))


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class DeployApplyUpdateView(generic.UpdateView):
    template_name = 'deploy/apply_update.html'
    model = DeployApply
    form_class = DeployApplyForm

    def get_success_url(self):
        self.success_url = '/deploy/apply_manage/'
        return self.success_url

    def get_context_data(self, **kwargs):
        context = super(DeployApplyUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['deploy_apply_form'] = DeployApplyForm(self.request.POST, instance=self.object)
            context['deploy_item_formset'] = DeployItemFormSet(self.request.POST, instance=self.object)
        else:
            context['deploy_apply_form'] = DeployApplyForm(instance=self.object)
            context['deploy_item_formset'] = DeployItemFormSet(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        deploy_apply_form = self.get_form(form_class)
        deploy_item_formset = DeployItemFormSet(self.request.POST)
        if (deploy_apply_form.is_valid()
                and deploy_item_formset.is_valid()):
            return self.form_valid(deploy_apply_form, deploy_item_formset)
        else:
            return self.form_invalid(deploy_apply_form, deploy_item_formset)

    def form_valid(self, deploy_apply_form, deploy_item_formset):
        self.object = deploy_apply_form.save()
        deploy_item_formset.instance = self.object
        deploy_item_formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, deploy_apply_form, deploy_item_formset):
        return self.render_to_response(
            self.get_context_data(deploy_apply_form=deploy_apply_form,
                                  deploy_item_formset=deploy_item_formset))

templates/deploy/apply_create.html
{% extends '__base__.html' %}
{% load staticfiles %}

{% block content %}

    <div class="app-title">
        {#            页面简介区域#}
        <div>
            <h1><i class="fa fa-th-list"></i> 填写发布申请单</h1>
            <p> 填写发布申请单，包括期望发布日期，发布涉及应用等</p>
        </div>
        {#            面包屑区域#}
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">发布申请管理</li>
            <li class="breadcrumb-item active">填写发布申请单</li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <form class="form-horizontal" action="{% url 'deploy:apply_create' %}" method="post">
                        {% csrf_token %}
                        {{ deploy_apply_form.management_form }}
                        {{ deploy_item_form.management_form }}
                        <div class="form-group row">
                            <label class="control-label col-md-2">申请项目名称</label>
                            <div class="col-md-5">
                                <input class="form-control {% if deploy_apply_form.errors.apply_project %}is-invalid{% endif %}"
                                       type="text" name="apply_project" placeholder="请输入项目名称">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">期望发布日期</label>
                            <div class="col-md-5">
                                <input class="form-control" id="demoDate" name="wish_deploy_time" type="text"
                                       placeholder="选择期望发布日期">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">配置修改说明</label>
                            <div class="col-md-5">
                                <textarea class="form-control" rows="10" type="text" name="conf_amend_explain"
                                          placeholder="请输入配置修改说明"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">备注事项</label>
                            <div class="col-md-5">
                                <textarea class="form-control" rows="10" type="text" name="remark_explain"
                                          placeholder="请输入备注事项"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">添加发布应用</label>
                            <div class="col-md-9">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                    <tr>
                                        {% for form in deploy_item_form %}
                                            {% if forloop.first %}
                                                {% for field in form %}
                                                    {% if field.label != "Id" and field.label != "所属发布申请单" %}
                                                        <th>{{ field.label }}</th>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        {% endfor %}
                                    </tr>
                                    </thead>
                                    <tbody id="id-deployitem-tbody">
                                    </tbody>
                                    <tfoot>
                                    <tr class="add-row">
                                        <td colspan="9"><a href="#" class="add-item">添加另一个 发布站点</a></td>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <div class="tile-footer">
                            <button class="btn btn-primary" type="submit" name="deploy_apply_create"><i
                                    class="fa fa-fw fa-lg fa-check-circle"></i>创建
                            </button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary"
                                                          href="{% url 'deploy:apply_manage' %}"><i
                                class="fa fa-fw fa-lg fa-times-circle"></i>返回</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block custom_static %}

    <!-- Page specific javascripts-->
    <script type="text/javascript" src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript">
        $('#sl').click(function () {
            $('#tl').loadingBtn();
            $('#tb').loadingBtn({text: "Signing In"});
        });

        $('#el').click(function () {
            $('#tl').loadingBtnComplete();
            $('#tb').loadingBtnComplete({html: "Sign In"});
        });

        $('#demoDate').datepicker({
            format: "dd/mm/yyyy",
            autoclose: true,
            todayHighlight: true
        });

        $('#demoSelect').select2();

    </script>

    <script type="text/html" id="item-template">
        <tr id="deployitem-set-__prefix__">
            <td>{{ deploy_item_form.empty_form.deploy_order_by }}</td>
            <td>{{ deploy_item_form.empty_form.jenkins_version }}</td>
            <td>{{ deploy_item_form.empty_form.deploy_application }}</td>
            <td>{{ deploy_item_form.empty_form.type }}</td>
            <td>{{ deploy_item_form.empty_form.DELETE }}</td>
            <td style="display: none">{{ deploy_item_form.empty_form.id }}</td>
            <td style="display: none">{{ deploy_item_form.empty_form.apply_project }}</td>
        </tr>
    </script>

    <script>
        $(document).ready(function () {
            $('.add-item').click(function (ev) {
                ev.preventDefault();
                var count = $('#id-deployitem-tbody').children().length;
                var tmplMarkup = $('#item-template').html();
                var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
                $('tbody#id-deployitem-tbody').append(compiledTmpl);

                //update form count
                $('#id_item_items-TOTAL_FORMS').attr('value', count + 1);

                // some animate to scroll to view our new form
                //  $('html, body').animate({
                //          scrollTop: $("#add-item-button").position().top-200
                //      }, 800);
            });
        });
    </script>

{% endblock %}

templates/deploy/apply_manage.html
{% extends '__base__.html' %}
{% load staticfiles %}

{% block content %}
    {% load group %}

    {#        表格有数据时展示#}
    <div class="app-title">
        {#            页面简介区域#}
        <div>
            <h1><i class="fa fa-th-list"></i> 发布申请管理</h1>
            {% if apply_manage %}
                <p> 填写、审核发布申请单，与发布相关的配置下发、SLB移除等操作</p>
            {% else %}
                <p>No apply are available.</p>
            {% endif %}
        </div>
        {#            面包屑区域#}
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item active">发布申请管理</li>
        </ul>
    </div>

    {#        按钮区域#}
    <div>
        <a class="btn btn-primary" type="button" href="{% url 'deploy:apply_create' %}">新增发布申请</a>
    </div>

    {% if apply_manage %}
        {#        表格区域#}
        <div class="row" id="loading">
            <div class="col-md-12">
                <div class="tile">
                    {#                    表格数据区域#}
                    <div class="tile-body table-responsive" id="table">
                        <table class="table table-hover table-bordered" id="sampleTable"
                               style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">
                            <thead>
                            <tr>
                                <th>申请编号</th>
                                <th>状态</th>
                                <th>申请人</th>
                                <th>申请时间</th>
                                <th>期望发布时间</th>
                                <th>发布人</th>
                                <th>实际发布时间</th>
                                <th class="text-center">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for apply in apply_manage %}
                                <tr>
                                    <td>
                                        <a href="{% url 'deploy:apply_update' apply.id %}">{{ apply.apply_project }}</a>
                                    </td>
                                    <td>
                                        {% if apply.status == "WC" %}
                                            <span>待提交</span>
                                        {% elif apply.status == "WD" %}
                                            <span>待发布</span>
                                        {% elif apply.status == "C" %}
                                            <span>已取消</span>
                                        {% elif apply.status == "D" %}
                                            <span>已发布</span>
                                        {% elif apply.status == "DA" %}
                                            <span>研发经理审批中</span>
                                        {% elif apply.status == "OA" %}
                                            <span>运维经理审批中</span>
                                        {% elif apply.status == "EA" %}
                                            <span>运维工程师审批中</span>
                                        {% elif apply.status == "TA" %}
                                            <span>测试经理审批中</span>
                                        {% elif apply.status == "TDA" %}
                                            <span>技术总监审批中</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ apply.apply_user }}
                                    </td>
                                    <td>
                                        {{ apply.apply_time|date:"Y-m-d H:i:s" }}
                                    </td>
                                    <td>
                                        {% if apply.wish_deploy_time is null %}
                                        {% else %}
                                            {{ apply.wish_deploy_time|date:"Y-m-d" }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if apply.deploy_user is null %}
                                        {% else %}
                                            {{ apply.deploy_user }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if apply.deploy_time is null %}
                                        {% else %}
                                            {{ apply.deploy_time }}
                                        {% endif %}
                                    </td>
                                    <td class="text-right">
                                        <!--修改按钮-->
                                        {% if apply.status == "WC" %}
                                            <a class="btn btn-success"
                                               href="{% url 'deploy:apply_update' apply.id %}">修改</a>
                                        {% endif %}
                                        <!--审核按钮-->
                                        {% if apply.status == "DA" %}
                                            {% if request.user.is_superuser or request.user|has_group:"admin" or request.user|has_group:"研发经理" %}
                                                <a class="btn btn-primary"
                                                   href="">研发经理审核</a>
                                            {% endif %}
                                        {% endif %}
                                        {% if apply.status == "TA" %}
                                            {% if request.user.is_superuser or request.user|has_group:"admin" or request.user|has_group:"测试经理" %}
                                                <a class="btn btn-primary"
                                                   href="">测试经理审核</a>
                                            {% endif %}
                                        {% endif %}
                                        {% if apply.status == "EA" %}
                                            {% if request.user.is_superuser or request.user|has_group:"admin" or request.user|has_group:"运维工程师" %}
                                                <a class="btn btn-primary"
                                                   href="">运维工程师审核</a>
                                            {% endif %}
                                        {% endif %}
                                        {% if apply.status == "OA" %}
                                            {% if request.user.is_superuser or request.user|has_group:"admin" or request.user|has_group:"运维经理" %}
                                                <a class="btn btn-primary"
                                                   href="">运维经理审核</a>
                                            {% endif %}
                                        {% endif %}
                                        {% if apply.status == "TDA" %}
                                            {% if request.user.is_superuser or request.user|has_group:"admin" or request.user|has_group:"技术总监" %}
                                                <a class="btn btn-primary"
                                                   href="">技术总监审核</a>
                                            {% endif %}
                                        {% endif %}
                                        <!--现在去发布按钮-->
                                        {% if request.user.is_superuser or request.user|has_group:"运维工程师" or request.user|has_group:"admin" %}
                                            {% if apply.status == 'WD' %}
                                                <a class="btn btn-info"
                                                   href="">现在去发布</a>
                                            {% endif %}
                                        {% endif %}
                                        <!--删除按钮-->
                                        {% if request.user.is_superuser or request.user|has_group:"admin" %}
                                            <a class="btn btn-danger" id="demoSwal{{ forloop.counter }}" href="#">删除</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-12">
                <div class="tile">
                    <div class="tile-body">请填写发布申请单</div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block custom_static %}

    <!-- Data table plugin-->
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>

    <!--Delete Alarm-->
    <script type="text/javascript" src="{% static 'js/plugins/sweetalert.min.js' %}"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });
        {% for apply in apply_manage %}
            $('#demoSwal{{ forloop.counter }}').click(function () {
                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this imaginary file!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel plx!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function (isConfirm) {
                    if (isConfirm) {
                        let postUrl = "{% url 'deploy:apply_delete' apply.id %}";
                        $.post(postUrl, function (data) {
                            if (data.success) {
                                swal("Deleted!", "Your imaginary file has been deleted.", "success");
                                location.reload();
                            }
                        })
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                });
            });
        {% endfor %}
    </script>

{% endblock %}