OperationManagementSystem/apps/system/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views


app_name = 'system'

urlpatterns = [
    # ECS
    url(r'^ecs/$', views.ECSListView.as_view(), name='ecs_manage'),
    url(r'^sync_all_ecs_from_acs/$', views.sync_all_ecs_from_acs, name='sync_all_ecs_from_acs'),
    url(r'^update_all_ecs_info/$', views.update_all_ecs_info, name='update_all_ecs_info'),
    url(r'^ecs_table_refresh/$', views.ecs_table_refresh, name='ecs_table_refresh'),
    url(r'^update_all_ecs_monitor/$', views.update_all_ecs_monitor, name='update_all_ecs_monitor'),
    # Application Race
    url(r'^application_race/$', views.ApplicationRaceListView.as_view(), name='application_race'),
    url(r'^application_race_add/$', views.application_race_add, name='application_race_add'),
    url(r'^application_race_edit/(?P<pk>[0-9]+)/$', views.ApplicationRaceEditView.as_view(),
        name='application_race_edit'),
    url(r'^application_race_save/(?P<application_race_id>[0-9]+)/$', views.application_race_save,
        name='application_race_save'),
    url(r'^application_race_delete/(?P<application_race_id>[0-9]+)/$', views.application_race_delete,
        name='application_race_delete'),
    # Application
    url(r'^application/$', views.ApplicationListView.as_view(), name='application_manage'),
    url(r'^application_add/$', views.ApplicationAdd.as_view(), name='application_add'),
    url(r'^application_delete/(?P<application_id>[0-9]+)/$', views.application_delete, name='application_delete'),
    url(r'^application_change/(?P<pk>[0-9]+)/$', views.ApplicationChangeView.as_view(),
        name='application_change'),
    url(r'^application_save/(?P<application_id>[0-9]+)/$', views.application_save, name='application_save'),
    # slb
    url(r'^slb_manage/$', views.SLBListView.as_view(), name='slb_manage'),
    url(r'^sync_all_slb_from_acs/$', views.update_all_slb_info, name='sync_all_slb_from_acs'),
    url(r'^one_slb_health_update/(?P<slb_id>[0-9]+)/$', views.one_slb_health_update, name='one_slb_health_update'),
    url(r'^all_slb_health_update/$', views.all_slb_health_update, name='all_slb_health_update'),
    url(r'^slb_add_backend_server/(?P<slb_id>[0-9]+)/(?P<server_id>[0-9]+)/$', views.slb_add_backend_server,
        name='slb_add_backend_server'),
    url(r'^slb_remove_backend_server/(?P<slb_id>[0-9]+)/(?P<server_id>[0-9]+)/$', views.slb_remove_backend_server,
        name='slb_add_backend_server'),
    url(r'^slb_change/(?P<slb_id>[0-9]+)$', views.SLBChangeView.as_view(), name='slb_change'),

]

OperationManagementSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from OperationManagementSystem.apps.dashboard.views import alarm_charts

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^system/', include('OperationManagementSystem.apps.system.urls')),
    url(r'^config/', include('OperationManagementSystem.apps.config.urls')),
    url(r'^operation/', include('OperationManagementSystem.apps.operation.urls')),
    url(r'^alarm/', include('OperationManagementSystem.apps.alarm.urls')),
    url(r'^dashboard/', include('OperationManagementSystem.apps.dashboard.urls')),
    url(r'^deploy/', include('OperationManagementSystem.apps.deploy.urls')),
    url(r'^oms_config_api/', include('OperationManagementSystem.apps.oms_config_api.urls')),
    url(r'^mychannels/', include('OperationManagementSystem.apps.mychannels.urls')),
    url(r'^jenkins/', include('OperationManagementSystem.apps.jenkins.urls')),
    url(r'^$', alarm_charts, name='index'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

OperationManagementSystem/apps/system/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class ECS(models.Model):
    ENABLE = 'Y'
    DISABLE = 'N'
    status_CHOICES = (
        (ENABLE, 'enable'),
        (DISABLE, 'disable'),
    )
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'ECS名称')
    instance_id = models.CharField(max_length=30, verbose_name=u'实例ID')
    IP = models.GenericIPAddressField(protocol='IPv4', null=True, blank=True, verbose_name=u'IP地址')
    status = models.CharField(
        max_length=1,
        choices=status_CHOICES,
        default=ENABLE,
    )
    modified_time = models.DateTimeField(auto_now=True, verbose_name=u'修改时间')
    recently_cpu = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name=u'最近CPU使用率')
    recently_memory = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True,
                                          verbose_name=u'最近内存使用率')
    recently_disk_usage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True,
                                              verbose_name=u'最近磁盘使用率')
    regionId = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'所在区域')
    expired_time = models.DateTimeField(null=True, blank=True, verbose_name=u'过期时间')
    memory = models.CharField(max_length=10, null=True, blank=True, verbose_name=u'内存大小')
    os_type = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'操作系统类型')
    instance_status = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'实例状态')
    network_type = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'网络类型')
    cpu = models.CharField(max_length=5, null=True, blank=True, verbose_name=u'CPU核数')
    public_ip_address = models.GenericIPAddressField(protocol='IPv4', null=True, blank=True, verbose_name=u'公网IP')
    osname = models.CharField(max_length=200, null=True, blank=True, verbose_name=u'操作系统名称')

    class Meta:
        verbose_name = u'ECS信息表'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class ApplicationRace(models.Model):
    race_id = models.BigIntegerField(verbose_name=u'随机应用族id')
    alias = models.CharField(max_length=50, null=True, blank=True, verbose_name=u'应用族别名')

    def get_application_id_list(self):
        return [str(a.id) for a in self.application_set.all()]

    class Meta:
        verbose_name = u'应用族群信息表'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.alias


class Application(models.Model):
    ENABLE = 'Y'
    DISABLE = 'N'
    status_CHOICES = (
        (ENABLE, 'enable'),
        (DISABLE, 'disable'),
    )
    fullname = models.CharField(max_length=50, verbose_name=u'应用全称')
    short_name = models.CharField(null=True, blank=True, max_length=30, verbose_name=u'应用简称')
    config_dir_name = models.CharField(null=True, blank=True, max_length=50, verbose_name=u'配置文件夹名称')
    ECS_lists = models.ManyToManyField(ECS, verbose_name=u'关联ECS列表')
    port = models.IntegerField(null=True, blank=True, verbose_name=u'应用端口')
    test_page = models.CharField(null=True, blank=True, max_length=30, verbose_name=u'测试页面')
    dev_charge = models.CharField(null=True, blank=True, max_length=10, verbose_name=u'研发负责人')
    deploy_attention = models.TextField(null=True, blank=True, verbose_name=u'发布注意事项')
    modified_time = models.DateTimeField(auto_now=True, verbose_name=u'修改时间')
    modified_user = models.CharField(max_length=20, default='admin', verbose_name=u'修改人')
    status = models.CharField(
        null=True, blank=True,
        max_length=1,
        choices=status_CHOICES,
        default=ENABLE,
        verbose_name=u'状态'
    )
    application_race = models.ForeignKey(ApplicationRace, on_delete=models.SET_NULL, null=True, blank=True,
                                         verbose_name=u'关联站点族')
    random_id = models.IntegerField(null=True, blank=True, verbose_name=u'应用随机ID')

    def get_config_files_name_by_semicolon(self):
        if self.configfile_set.all():
            return ';'.join([config_file.filename for config_file in self.configfile_set.all()])
        else:
            return []

    def get_config_files_name_list(self):
        if self.configfile_set.all():
            return [config_file.filename for config_file in self.configfile_set.all()]
        else:
            return []

    def get_ecs_id_list(self):
        if self.ECS_lists.all():
            return [str(ecs.id) for ecs in self.ECS_lists.all()]
        else:
            return []

    class Meta:
        verbose_name = u'应用信息表'

    def __unicode__(self):
        return self.fullname


class SLB(models.Model):
    instance_id = models.CharField(max_length=50, verbose_name=u'实例ID')
    name = models.CharField(max_length=50, verbose_name=u'实例名称')
    status = models.CharField(max_length=30, verbose_name=u'实例状态')
    ip = models.GenericIPAddressField(protocol='IPv4', verbose_name=u'IP地址')
    network_type = models.CharField(max_length=10, null=True, blank=True, verbose_name=u'网络类型')
    address_type = models.CharField(max_length=10, verbose_name=u'IP类型类型')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')

    class Meta:
        verbose_name = u'负载均衡信息表'
        verbose_name_plural = verbose_name

    def get_application_id_list(self):
        return [int(application.application_id) for application in self.slbtoapplication_set.all()]

    def __unicode__(self):
        return self.name


class RDS(models.Model):
    instance_id = models.CharField(max_length=100, verbose_name=u'实例ID')
    instance_alias = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'实例别名')
    network_type = models.CharField(max_length=20, verbose_name=u'网络类型')
    engine = models.CharField(max_length=30, verbose_name=u'引擎类型')
    engine_version = models.CharField(max_length=50, verbose_name=u'引擎版本')
    status = models.CharField(max_length=30, verbose_name=u'状态')
    expire_time = models.DateTimeField(verbose_name=u'过期时间')

    class Meta:
        verbose_name = u'RDS信息表'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.instance_id


class RDSUsageRecord(models.Model):
    rds = models.ForeignKey(RDS, on_delete=models.CASCADE, verbose_name=u'所属RDS')
    cpu_usage = models.FloatField(null=True, blank=True, verbose_name=u'CPU使用率')
    io_usage = models.FloatField(null=True, blank=True, verbose_name=u'IOPS使用率')
    disk_usage = models.FloatField(null=True, blank=True, verbose_name=u'磁盘使用率')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'RDS资源使用率记录表'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.add_time)

OperationManagementSystem/apps/system/forms.py
# -*- coding: utf-8 -*-

from django import forms
from OperationManagementSystem.apps.system.models import Application


class ApplicationForm(forms.ModelForm):
    fullname = forms.CharField(required=True, max_length=50)

    class Meta:
        model = Application
        exclude = ['ECS_lists', 'modified_user', 'modified_time', 'application_race']

templates/system/application_add.html
{% extends '__base__.html' %}
{% load staticfiles %}

{% block content %}

    {#    页面头部#}
    <div class="app-title">
        {#            页面简介区域#}
        <div>
            <h1><i class="fa fa-edit"></i> 添加应用</h1>
            <p> 添加 IIS 站点、Java 应用</p>
        </div>
        {#            面包屑区域#}
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">系统管理</li>
            <li class="breadcrumb-item"><a href="{% url 'system:application_manage' %}">应用管理</a></li>
            <li class="breadcrumb-item active"><a href="#">添加应用</a></li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <form class="form-horizontal" action="{% url 'system:application_add' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="control-label col-md-2">应用名称</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="fullname" placeholder="请输入站点名称">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">应用简称</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="short_name" placeholder="请输入站点简称">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">配置文件夹名称</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="config_dir_name" placeholder="请输入配置文件夹名称">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">配置文件</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="config_files"
                                       placeholder="请输入配置文件,以分号;隔开">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">所属 ECS</label>
                            <div class="col-md-8">
                                <select class="form-control" id="demoSelect1" multiple="multiple" name="select_ecs[]">
                                    <optgroup label="选择所属 ECS">
                                        {% for ecs in ecs_list %}
                                            <option value="{{ ecs.id }}">{{ ecs.name }}</option>
                                        {% endfor %}
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">所属应用族</label>
                            <div class="col-md-8">
                                <select class="form-control" id="demoSelect2" name="select_application_race">
                                    <optgroup label="选择所属应用族">
                                        <option value="0">...</option>
                                        {% for application_race in application_race_list %}
                                            <option value="{{ application_race.id }}">{{ application_race.alias }}</option>
                                        {% endfor %}
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">端口号</label>
                            <div class="col-md-5">
                                <input class="form-control" type="number" name="port" placeholder="请输入端口号">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">测试页面</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="test_page" placeholder="请输入测试页面">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">状态</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input name="status" value="Y" class="form-check-input" type="radio" checked>启用
                                </label>
                            </div>&nbsp;&nbsp;
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input name="status" value="N" class="form-check-input" type="radio">禁用
                                </label>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">研发负责人</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="dev_charge" placeholder="请输入研发负责人">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">发布注意事项</label>
                            <div class="col-md-8">
                            <textarea class="form-control" rows="4" name="deploy_attention"
                                      placeholder="请输入发布注意事项"></textarea>
                            </div>
                        </div>
                        <div class="tile-footer">
                            <button class="btn btn-primary" type="submit" name="application_add"><i
                                    class="fa fa-fw fa-lg fa-check-circle"></i>新增
                            </button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary"
                                                          href="{% url 'system:application_manage' %}"><i
                                class="fa fa-fw fa-lg fa-times-circle"></i>返回</a>
                        </div>
                        <input type="hidden" name="modified_user" value="{{ request.user.username }}">
                        <input type="hidden" name="random_id" value="">
                    </form>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block custom_static %}

    <script type="text/javascript" src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/select2.min.js' %}"></script>
    <script type="text/javascript">
        $('#sl').click(function () {
            $('#tl').loadingBtn();
            $('#tb').loadingBtn({text: "Signing In"});
        });

        $('#el').click(function () {
            $('#tl').loadingBtnComplete();
            $('#tb').loadingBtnComplete({html: "Sign In"});
        });

        $('#demoDate').datepicker({
            format: "dd/mm/yyyy",
            autoclose: true,
            todayHighlight: true
        });

        $('#demoSelect1').select2();
        $('#demoSelect2').select2();
    </script>

{% endblock %}

templates/system/application_change.html
{% extends '__base__.html' %}
{% load staticfiles %}

{% block content %}

    <div class="app-title">
        {#            页面简介区域#}
        <div>
            <h1><i class="fa fa-th-list"></i> 修改应用</h1>
            <p> 修改应用基本信息</p>
        </div>
        {#            面包屑区域#}
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">系统管理</li>
            <li class="breadcrumb-item"><a href="{% url 'system:application_manage' %}">应用管理</a></li>
            <li class="breadcrumb-item active"><a href="#">修改应用</a></li>
        </ul>
    </div>
    {#        操作结果提示栏区域#}
    <div class="row">
        <div class="col-lg-12">
            <div class="bs-component">
                <div class="alert alert-dismissible" id="notice" style="display: none;">
                    <button class="close" type="button" data-dismiss="alert">×</button>
                    <h4></h4>
                    <p><a class="alert-link" href="#"></a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    {#    表单区域#}
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <form class="form-horizontal" action="{% url 'system:application_save' application.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="control-label col-md-2">应用名称</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="fullname"
                                       value="{{ application.fullname }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">应用简称</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="short_name"
                                       value="{{ application.short_name }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">配置文件夹名称</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="config_dir_name"
                                       value="{{ application.config_dir_name }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">配置文件</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="config_files"
                                       value="{{ application.get_config_files_name_by_semicolon }}">
                                <small class="form-text text-muted" id="fileHelp">请输入配置文件，以英文分号;隔开</small>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">所属 ECS</label>
                            <div class="col-md-8">
                                <select class="form-control" id="demoSelect1" multiple="multiple" name="select_ecs[]">
                                    <optgroup label="选择所属 ECS">
                                        {% for ecs in ecs_list %}
                                            <option value="{{ ecs.id }}"
                                                    {% if ecs in application.ECS_lists.all %}selected{% endif %}>{{ ecs.name }}</option>
                                        {% endfor %}
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">所属应用族</label>
                            <div class="col-md-8">
                                <select class="form-control" id="demoSelect2" name="select_application_race">
                                    <optgroup label="选择所属应用族">
                                        <option value="0">...</option>
                                        {% for application_race in application_race_list %}
                                            <option value="{{ application_race.id }}"
                                                    {% if application.application_race_id == application_race.id %}selected{% endif %}>{{ application_race.alias }}</option>
                                        {% endfor %}
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">端口号</label>
                            <div class="col-md-5">
                                <input class="form-control" type="number" name="port" value="{{ application.port }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">测试页面</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="test_page"
                                       value="{{ application.test_page }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">状态</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input name="status" value="Y" class="form-check-input" type="radio"
                                           {% if application.status == "Y" %}checked{% endif %}>启用
                                </label>
                            </div>&nbsp;&nbsp;
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input name="status" value="N" class="form-check-input" type="radio"
                                           {% if application.status == "N" %}checked{% endif %}>禁用
                                </label>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">研发负责人</label>
                            <div class="col-md-5">
                                <input class="form-control" type="text" name="dev_charge" value="{{ application.dev_charge }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">发布注意事项</label>
                            <div class="col-md-8">
                            <textarea class="form-control" rows="4" name="deploy_attention"
                                      value="{{ application.deploy_attention }}">{{ application.deploy_attention }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">修改人</label>
                            <div class="col-md-5">
                                {{ application.modified_user }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">修改时间</label>
                            <div class="col-md-5">
                                {{ application.modified_time|date:"Y-m-d H:i:s" }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">配置文件修改记录</label>
                            <div class="col-md-5">

                            </div>
                        </div>
                        <div class="tile-footer">
                            <button class="btn btn-primary" type="submit" name="application_save"><i
                                    class="fa fa-fw fa-lg fa-check-circle"></i>保存
                            </button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary"
                                                          href="{% url 'system:application_manage' %}"><i
                                class="fa fa-fw fa-lg fa-times-circle"></i>返回</a>
                        </div>
                        <input type="hidden" name="modified_user" value="{{ request.user.username }}">
                        <input type="hidden" name="random_id" value="">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block custom_static %}

    <script type="text/javascript" src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/select2.min.js' %}"></script>
    <script type="text/javascript">
        $('#sl').click(function () {
            $('#tl').loadingBtn();
            $('#tb').loadingBtn({text: "Signing In"});
        });

        $('#el').click(function () {
            $('#tl').loadingBtnComplete();
            $('#tb').loadingBtnComplete({html: "Sign In"});
        });

        $('#demoDate').datepicker({
            format: "dd/mm/yyyy",
            autoclose: true,
            todayHighlight: true
        });

        $('#demoSelect1').select2();
        $('#demoSelect2').select2();
    </script>

{% endblock %}

templates/system/ecs_table_data.html
<table class="table table-hover table-bordered" id="sampleTable"
       style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">
    <thead>
    <tr>
        <th>区域</th>
        <th>网络类型</th>
        <th>ECS名称</th>
        <th>实例ID</th>
        <th>系统类型</th>
        <th>系统版本</th>
        <th>内网IP地址</th>
        <th>外网IP地址</th>
        <th>配置规格</th>
        <th>使用状态</th>
        <th>运行状态</th>
        <th>过期时间</th>
        <th>修改日期</th>
        <th>CPU使用率</th>
        <th>内存使用率</th>
        <th>磁盘使用率</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for ecs in ecs_manage %}
        <tr>
            <td>{{ ecs.regionId }}</td>
            <td>{{ ecs.networktype }}</td>
            <td>{{ ecs.name }}</td>
            <td>{{ ecs.instanceid }}</td>
            <td>{{ ecs.ostype }}</td>
            <td>{{ ecs.osname }}</td>
            <td>{{ ecs.IP }}</td>
            <td>{{ ecs.publicipaddress }}</td>
            <td>CPU:{{ ecs.cpu }}核 内存:{{ ecs.memory }}G</td>
            <td>
                {% if ecs.status == 'Y' %}<span>启用</span>
                {% else %}<span class="text-danger"><strong>禁用</strong></span>
                {% endif %}
            </td>
            <td>{{ ecs.instancestatus }}</td>
            <td>{{ ecs.expiredtime }}</td>
            <td>{{ ecs.modified_time }}</td>
            <td>{{ ecs.recently_cpu }}</td>
            <td>{{ ecs.recently_memory }}</td>
            <td>{{ ecs.recently_disk_usage }}</td>
            <td>

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>