OperationManagementSystem/apps/config/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'config'

urlpatterns = [
    url(r'^configfile/$', views.ConfigfileListView.as_view(), name='configfile'),
    url(r'^config_change/(?P<pk>[0-9]+)/$', views.ConfigChangeDetailView.as_view(), name='config_change'),
    url(r'^config_change_save/(?P<configfile_id>[0-9]+)/$', views.configfile_change_save, name='config_change_save'),
    url(r'^config_history_manage/(?P<configfile_id>[0-9]+)/$', views.config_history_manage,
        name='config_history_manage'),
    url(r'^config_history_detail/(?P<pk>[0-9]+)/$', views.ConfigHistoryDetailView.as_view(),
        name='config_history_detail'),
    url(r'^config_recover/(?P<history_id>[0-9]+)/$', views.config_recover, name='config_recover'),
]

OperationManagementSystem/apps/deploy/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'deploy'

urlpatterns = [
    url(r'^apply_manage/$', views.DeployApplyListView.as_view(), name='apply_manage'),
    url(r'^apply_delete/(?P<apply_id>[0-9]+)/$', views.deploy_apply_delete, name='apply_delete'),
    url(r'^apply_create/$', views.DeployApplyCreateView.as_view(), name='apply_create'),
    url(r'^apply_update/(?P<pk>[0-9]+)/$', views.DeployApplyUpdateView.as_view(), name='apply_update'),
]

OperationManagementSystem/apps/jenkins/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'jenkins'

urlpatterns = [
    url(r'^jenkins_job_list/$', views.JenkinsJobListView.as_view(), name='jenkins_job_list'),
    url(r'^build/(?P<job_id>[0-9]+)/$', views.build, name='build'),
    url(r'^job_history/(?P<job_id>[0-9]+)/$', views.job_history, name='job_history'),
    url(r'^sync_jenkins_jobs/$', views.sync_jenkins_jobs, name='sync_jenkins_jobs'),
]

OperationManagementSystem/apps/system/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views


app_name = 'system'

urlpatterns = [
    # ECS
    url(r'^ecs/$', views.ECSListView.as_view(), name='ecs_manage'),
    url(r'^sync_all_ecs_from_acs/$', views.sync_all_ecs_from_acs, name='sync_all_ecs_from_acs'),
    url(r'^update_all_ecs_info/$', views.update_all_ecs_info, name='update_all_ecs_info'),
    url(r'^ecs_table_refresh/$', views.ecs_table_refresh, name='ecs_table_refresh'),
    url(r'^update_all_ecs_monitor/$', views.update_all_ecs_monitor, name='update_all_ecs_monitor'),
    # Application Race
    url(r'^application_race/$', views.ApplicationRaceListView.as_view(), name='application_race'),
    url(r'^application_race_add/$', views.application_race_add, name='application_race_add'),
    url(r'^application_race_edit/(?P<pk>[0-9]+)/$', views.ApplicationRaceEditView.as_view(),
        name='application_race_edit'),
    url(r'^application_race_save/(?P<application_race_id>[0-9]+)/$', views.application_race_save,
        name='application_race_save'),
    url(r'^application_race_delete/(?P<application_race_id>[0-9]+)/$', views.application_race_delete,
        name='application_race_delete'),
    # Application
    url(r'^application/$', views.ApplicationListView.as_view(), name='application_manage'),
    url(r'^application_add/$', views.ApplicationAdd.as_view(), name='application_add'),
    url(r'^application_delete/(?P<application_id>[0-9]+)/$', views.application_delete, name='application_delete'),
    url(r'^application_change/(?P<pk>[0-9]+)/$', views.ApplicationChangeView.as_view(),
        name='application_change'),
    url(r'^application_save/(?P<application_id>[0-9]+)/$', views.application_save, name='application_save'),
    # slb
    url(r'^slb_manage/$', views.SLBListView.as_view(), name='slb_manage'),
    url(r'^sync_all_slb_from_acs/$', views.update_all_slb_info, name='sync_all_slb_from_acs'),
    url(r'^one_slb_health_update/(?P<slb_id>[0-9]+)/$', views.one_slb_health_update, name='one_slb_health_update'),
    url(r'^all_slb_health_update/$', views.all_slb_health_update, name='all_slb_health_update'),
    url(r'^slb_add_backend_server/(?P<slb_id>[0-9]+)/(?P<server_id>[0-9]+)/$', views.slb_add_backend_server,
        name='slb_add_backend_server'),
    url(r'^slb_remove_backend_server/(?P<slb_id>[0-9]+)/(?P<server_id>[0-9]+)/$', views.slb_remove_backend_server,
        name='slb_add_backend_server'),
    url(r'^slb_change/(?P<slb_id>[0-9]+)$', views.SLBChangeView.as_view(), name='slb_change'),

]

OperationManagementSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from OperationManagementSystem.apps.dashboard.views import alarm_charts

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^system/', include('OperationManagementSystem.apps.system.urls')),
    url(r'^config/', include('OperationManagementSystem.apps.config.urls')),
    url(r'^operation/', include('OperationManagementSystem.apps.operation.urls')),
    url(r'^alarm/', include('OperationManagementSystem.apps.alarm.urls')),
    url(r'^dashboard/', include('OperationManagementSystem.apps.dashboard.urls')),
    url(r'^deploy/', include('OperationManagementSystem.apps.deploy.urls')),
    url(r'^oms_config_api/', include('OperationManagementSystem.apps.oms_config_api.urls')),
    url(r'^mychannels/', include('OperationManagementSystem.apps.mychannels.urls')),
    url(r'^jenkins/', include('OperationManagementSystem.apps.jenkins.urls')),
    url(r'^$', alarm_charts, name='index'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

templates/__base__.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta name="description" content="运维管理平台">
    <title>{% block title %}运维管理平台{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body class="app sidebar-mini rtl">

<!-- NavBar-->
<header class="app-header"><a class="app-header__logo" href="{% url 'index' %}">ShineTour</a>
    <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar"
                                    aria-label="Hide Sidebar"></a>
    <!-- NavBar Right Menu-->
    <ul class="app-nav">
        <li class="app-search">
            <input class="app-search__input" type="search" placeholder="Search">
            <button class="app-search__button"><i class="fa fa-search"></i></button>
        </li>
        <!-- User Menu-->
        <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i
                class="fa fa-user fa-lg"></i></a>
            <ul class="dropdown-menu settings-menu dropdown-menu-right">
                <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out fa-lg"></i> Logout</a>
                </li>
            </ul>
        </li>
    </ul>
</header>

<!-- Sidebar menu-->
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
<aside class="app-sidebar">
    <div class="app-sidebar__user"><img class="app-sidebar__user-avatar"
                                        src="{% static 'image/48.jpg' %}"
                                        alt="User Image">
        <div>
            <p class="app-sidebar__user-name">{{ user.username }}</p>
            <p class="app-sidebar__user-designation">{{ user.groups.all.0 }}</p>
        </div>
    </div>
    <ul class="app-menu">
        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">仪表盘</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
            <ul class="treeview-menu">
                <li><a class="treeview-item" href="{% url 'dashboard:alarm_charts' %}"><i class="icon fa fa-circle-o"></i> 报警-统计报表</a></li>
                <li><a class="treeview-item" href="{% url 'dashboard:rds_charts' %}"><i class="icon fa fa-circle-o"></i> RDS-统计报表</a></li>
                <li><a class="treeview-item" href=""><i class="icon fa fa-circle-o"></i> ECS-统计报表</a></li>
            </ul>
        </li>
        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-laptop"></i><span class="app-menu__label">系统管理</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
            <ul class="treeview-menu">
                <li><a class="treeview-item" href="{% url 'system:ecs_manage' %}"><i class="icon fa fa-circle-o"></i>
                    ECS管理</a></li>
                <li><a class="treeview-item" href="{% url 'system:application_race' %}"><i
                        class="icon fa fa-circle-o"></i> 应用族管理</a></li>
                <li><a class="treeview-item" href="{% url 'system:application_manage' %}"><i
                        class="icon fa fa-circle-o"></i> 应用管理</a></li>
                <li><a class="treeview-item" href="{% url 'system:slb_manage' %}"><i class="icon fa fa-circle-o"></i>
                    SLB管理</a></li>
            </ul>
        </li>
        <li><a class="app-menu__item" href="{% url 'config:configfile' %}"><i class="app-menu__icon fa fa-edit"></i><span
                class="app-menu__label"> 配置管理</span></a></li>
        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-adjust"></i><span class="app-menu__label"> 发布管理</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
            <ul class="treeview-menu">
                <li><a class="treeview-item" href="{% url 'deploy:apply_manage' %}"><i class="icon fa fa-circle-o"></i> 发布申请管理</a></li>
                <li><a class="treeview-item" href="{% url 'jenkins:jenkins_job_list' %}"><i class="icon fa fa-circle-o"></i> Jenkins任务管理</a></li>
                <li><a class="treeview-item" href="{% url 'mychannels:config_deploy_record' %}"><i class="icon fa fa-circle-o"></i> 发布实时日志</a></li>
            </ul>
        </li>
        <li><a class="app-menu__item" href=""><i class="app-menu__icon fa fa-exclamation-triangle"></i><span
                class="app-menu__label">报警管理</span></a></li>
        <li><a class="app-menu__item" href="/admin/"><i class="app-menu__icon fa fa-inbox"></i><span
                class="app-menu__label">后台管理</span></a></li>
        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-laptop"></i><span class="app-menu__label">API管理</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
            <ul class="treeview-menu">
                <li><a class="treeview-item" href="{% url 'oms_config_api:deploy_config' %}"><i class="icon fa fa-circle-o"></i>
                    接收配置文件API</a></li>
            </ul>
        </li>
    </ul>
</aside>

<main class="app-content">
    {% block content %}{% endblock %}
</main>


<!-- Essential JavaScripts for application to work-->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!--引用jquery ShowLoading-->
<link href="{% static 'css/showLoading.css' %}" rel="stylesheet" media="screen"/>
<script src="{% static 'js/jquery.showLoading.min.js' %}"></script>
<!-- Page specific JavaScripts-->
{% block custom_static %}{% endblock %}

</body>
</html>

templates/index.html
{% extends '__base__.html' %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>登录 | 运维管理平台</title>
</head>
<body>
<section class="material-half-bg">
    <div class="cover"></div>
</section>
<section class="login-content">
    <div class="logo">
        <h1>OMS</h1>
    </div>
    <div class="login-box">
        <form class="login-form" action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>登录</h3>
            <div class="form-group">
                <label class="control-label">用户名</label>
                <input class="form-control" type="text" name="username" placeholder="请输入用户名 或 邮箱" autofocus>
            </div>
            <div class="form-group">
                <label class="control-label">密码</label>
                <input class="form-control" type="password" name="password" placeholder="请输入密码">
            </div>
            <div class="form-group">
                <div class="utility">
                    <div class="animated-checkbox">
                        <label>
                            <input type="checkbox"><span class="label-text">Stay Signed in</span>
                        </label>
                    </div>
                    <p class="semibold-text mb-2"><a href="#" data-toggle="flip">Forgot Password ?</a></p>
                </div>
            </div>
            <div class="form-group btn-container">
                <button class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>登录</button>
            </div>
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        </form>
        <form class="forget-form" action="index.html">
            <h3 class="login-head"><i class="fa fa-lg fa-fw fa-lock"></i>Forgot Password ?</h3>
            <div class="form-group">
                <label class="control-label">EMAIL</label>
                <input class="form-control" type="text" placeholder="Email">
            </div>
            <div class="form-group btn-container">
                <button class="btn btn-primary btn-block"><i class="fa fa-unlock fa-lg fa-fw"></i>RESET</button>
            </div>
            <div class="form-group mt-3">
                <p class="semibold-text mb-0"><a href="#" data-toggle="flip"><i class="fa fa-angle-left fa-fw"></i> Back
                    to Login</a></p>
            </div>
        </form>
    </div>
</section>
<!-- Essential JavaScripts for application to work-->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The JavaScript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js' %}"></script>
<script type="text/javascript">
    // Login Page Flipbox control
    $('.login-content [data-toggle="flip"]').click(function () {
        $('.login-box').toggleClass('flipped');
        return false;
    });
</script>
</body>
</html>