OperationManagementSystem/apps/alarm/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'alarm'

urlpatterns = [

]

OperationManagementSystem/apps/dashboard/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from apscheduler.schedulers.background import BackgroundScheduler
from . import views
from . import cron

app_name = 'dashboard'

urlpatterns = [
    # alarm
    url(r'^alarm_charts/$', views.alarm_charts, name='alarm_charts'),
    url(r'^index_alarm_product_type_pie/$', views.index_alarm_product_type_pie, name='index_alarm_product_type_pie'),
    url(r'^index_alarm_metric_type_pie/$', views.index_alarm_metric_type_pie, name='index_alarm_metric_type_pie'),
    url(r'^index_alarm_instance_pie/$', views.index_alarm_instance_pie, name='index_alarm_instance_pie'),
    url(r'^index_alarm_line/$', views.index_alarm_line, name='index_alarm_line'),
    # rds
    url(r'^rds_charts/$', views.rds_charts, name='rds_charts'),
    url(r'^index_rds_cpu_pie/$', views.index_rds_cpu_pie, name='index_rds_cpu_pie'),
    url(r'^index_rds_io_pie/$', views.index_rds_io_pie, name='index_rds_io_pie'),
    url(r'^index_rds_disk_pie/$', views.index_rds_disk_pie, name='index_rds_disk_pie'),
    url(r'^index_rds_line/$', views.index_rds_line, name='index_rds_line'),
]


scheduler = BackgroundScheduler()


@scheduler.scheduled_job("interval", seconds=500, id="get_alarm_history")
def get_alarm_history():
    cron.get_alarm_history_list()
    print ("get_alarm_history")


@scheduler.scheduled_job("interval", seconds=600, id="get_rds_info")
def get_rds_info():
    cron.get_rds_info()
    print ('Update RDS Info')


@scheduler.scheduled_job("interval", seconds=300, id="get_rds_monitor")
def get_rds_monitor():
    cron.get_rds_monitor()
    print ('get_rds_monitor')


scheduler.start()

OperationManagementSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from OperationManagementSystem.apps.dashboard.views import alarm_charts

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^system/', include('OperationManagementSystem.apps.system.urls')),
    url(r'^config/', include('OperationManagementSystem.apps.config.urls')),
    url(r'^operation/', include('OperationManagementSystem.apps.operation.urls')),
    url(r'^alarm/', include('OperationManagementSystem.apps.alarm.urls')),
    url(r'^dashboard/', include('OperationManagementSystem.apps.dashboard.urls')),
    url(r'^deploy/', include('OperationManagementSystem.apps.deploy.urls')),
    url(r'^oms_config_api/', include('OperationManagementSystem.apps.oms_config_api.urls')),
    url(r'^mychannels/', include('OperationManagementSystem.apps.mychannels.urls')),
    url(r'^jenkins/', include('OperationManagementSystem.apps.jenkins.urls')),
    url(r'^$', alarm_charts, name='index'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

OperationManagementSystem/apps/alarm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class AlarmHistory(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'告警规则名称')
    namespace = models.CharField(max_length=30, verbose_name=u'告警产品名称')
    alarm_time = models.DateTimeField(null=True, blank=True, verbose_name=u'告警时间')
    value = models.CharField(max_length=10, verbose_name=u'告警的当前值')
    instance_name = models.CharField(max_length=50, verbose_name=u'告警实例名称')
    metric_name = models.CharField(max_length=50, verbose_name=u'监控项名称')
    dimension = models.CharField(max_length=200, verbose_name=u'告警详情')

    class Meta:
        verbose_name = u'告警历史'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

OperationManagementSystem/apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

OperationManagementSystem/apps/alarm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

OperationManagementSystem/apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from OperationManagementSystem.apps.alarm.models import AlarmHistory
from OperationManagementSystem.apps.system.models import RDSUsageRecord
from django.http import HttpResponse
from django.db.models import Count, Avg
import datetime
import json

app_name = 'dashboard'


@login_required(login_url='/login/')
def alarm_charts(request):
    return render(request, 'dashboard/alarm.html', {})


@login_required(login_url='/login/')
def index_alarm_product_type_pie(request):
    # 按alarm产品类型统计（默认为最近30天）
    now = datetime.datetime.now()
    ever = now - datetime.timedelta(days=30)
    alarm = AlarmHistory.objects.filter(alarm_time__gt=ever).values('namespace').annotate(Count("id"))
    product_type_list = []
    for i in alarm:
        product_type_list.append(str(i['namespace']))
    product_type_alarm_list = []
    for i in alarm:
        product_type_dict = {str('value'): i['id__count'], str('name'): str(i['namespace'])}
        product_type_alarm_list.append(product_type_dict)
    return HttpResponse(json.dumps({'success': True, 'product_type_list': product_type_list,
                                    'product_type_alarm_list': product_type_alarm_list}),
                        content_type="application/json")


@login_required(login_url='/login/')
def index_alarm_metric_type_pie(request):
    # 按alarm监控项类型统计（默认为最近30天）
    now = datetime.datetime.now()
    ever = now - datetime.timedelta(days=30)
    alarm = AlarmHistory.objects.filter(alarm_time__gt=ever).values('metric_name').annotate(Count("id"))
    metric_type_list = []
    for i in alarm:
        metric_type_list.append(str(i['metric_name']))
    metric_type_alarm_list = []
    for i in alarm:
        metric_type_dict = {str('value'): i['id__count'], str('name'): str(i['metric_name'])}
        metric_type_alarm_list.append(metric_type_dict)
    return HttpResponse(json.dumps({'success': True, 'metric_type_list': metric_type_list,
                                    'metric_type_alarm_list': metric_type_alarm_list}),
                        content_type="application/json")


@login_required(login_url='/login/')
def index_alarm_instance_pie(request):
    # 按alarm实例比例统计（默认为最近30天）
    now = datetime.datetime.now()
    ever = now - datetime.timedelta(days=30)
    alarm = AlarmHistory.objects.filter(alarm_time__gt=ever).values('instance_name').annotate(Count("id"))
    instance_list = []
    for i in alarm:
        instance_list.append(i['instance_name'])
    instance_alarm_list = []
    for i in alarm:
        instance_dict = {'value': i['id__count'], 'name': i['instance_name']}
        instance_alarm_list.append(instance_dict)
    return HttpResponse(json.dumps({'success': True, 'instance_list': instance_list,
                                    'instance_alarm_list': instance_alarm_list}),
                        content_type="application/json")


@login_required(login_url='/login/')
def index_alarm_line(request):
    start = str(datetime.datetime.now())[:4] + '-01-01'
    end = str(datetime.datetime.now())[:4] + '-12-31'
    alarm = AlarmHistory.objects.filter(alarm_time__gt=start).filter(alarm_time__lt=end). \
        extra(select={'month': 'month(alarm_time)'}).values('month').annotate(number=Count('id'))
    alarm_num_x = []
    alarm_num_y = []
    this_year = str(datetime.datetime.now())[:4]
    for m in xrange(1, 13):
        this_date = this_year + '-' + str(m)
        alarm_num_x.append(this_date)
    for m in xrange(1, 13):
        try:
            dict_index = [int(a['month']) for a in alarm].index(m)
        except Exception, e:
            alarm_num_y.append(0)
            print e
        else:
            alarm_num_y.append([a for a in alarm][dict_index]['number'])
    return HttpResponse(json.dumps({'success': True, 'alarm_num_x': alarm_num_x, 'alarm_num_y': alarm_num_y}),
                        content_type="application/json")


@login_required(login_url='/login/')
def rds_charts(request):
    return render(request, 'dashboard/rds.html', {})


@login_required(login_url='/login/')
def index_rds_cpu_pie(request):
    # 获取最近一次rds资源
    last_rds_resource = RDSUsageRecord.objects.order_by('-add_time')[:1]
    # 获取最近一次rds资源cpu使用率
    try:
        last_rds_cpu = [q.cpu_usage for q in last_rds_resource][0]
    except:
        return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': True, 'last_rds_cpu': last_rds_cpu}),
                            content_type="application/json")


@login_required(login_url='/login/')
def index_rds_io_pie(request):
    # 获取最近一次rds资源
    last_rds_resource = RDSUsageRecord.objects.order_by('-add_time')[:1]
    # 获取最近一次rds资源IO使用率
    try:
        last_rds_io = [q.io_usage for q in last_rds_resource][0]
    except:
        return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': True, 'last_rds_io': last_rds_io}), content_type="application/json")


@login_required(login_url='/login/')
def index_rds_disk_pie(request):
    # 获取最近一次rds资源
    last_rds_resource = RDSUsageRecord.objects.order_by('-add_time')[:1]
    # 获取最近一次rds资源IO使用率
    try:
        last_rds_disk = [q.disk_usage for q in last_rds_resource][0]
    except:
        return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': True, 'last_rds_disk': last_rds_disk}),
                            content_type="application/json")


@login_required(login_url='/login/')
def index_rds_line(request):
    # 默认横坐标间隔
    select_count = 12
    select_range = request.POST['select_range']
    if select_range == u'1小时':
        select_count = 12
    if select_range == u'6小时':
        select_count = 72
    if select_range == u'12小时':
        select_count = 144
    if select_range == u'1天':
        select_count = 288
    if select_range == u'3天':
        select_count = 864
    if select_range == u'7天':
        select_count = 2016
    if select_range == u'14天':
        select_count = 4032
    try:
        # 获取最近12次rds资源, 默认5分钟为间隔
        recently_rds_resource = RDSUsageRecord.objects.order_by('-add_time')[:select_count]
        # 获取最近12次add_time的list
        add_time_list = [q.add_time.strftime('%Y-%m-%d %H:%M') for q in recently_rds_resource]
        add_time_list.sort()
        add_time = add_time_list
        # 获取最近12次rds的CPU使用率list
        recently_rds_cpu = [q.cpu_usage for q in recently_rds_resource]
        recently_rds_cpu.reverse()
        # 获取最近12次rds的I/O使用率list
        recently_rds_io = [q.io_usage for q in recently_rds_resource]
        recently_rds_io.reverse()
        # 获取最近12次rds的disk使用率list
        recently_rds_disk = [q.disk_usage for q in recently_rds_resource]
        recently_rds_disk.reverse()
    except:
        return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': True, 'add_time': add_time,
                                        'recently_rds_cpu': recently_rds_cpu, 'recently_rds_io': recently_rds_io,
                                        'recently_rds_disk': recently_rds_disk}), content_type="application/json")

templates/dashboard/alarm.html
{% extends '__base__.html' %}
{% load staticfiles %}

{% block content %}

    <!-- 每60s刷新一次页面 -->
    <meta http-equiv="refresh" content="60">

    <div class="app-title">
        {#            页面简介区域#}
        <div>
            <h1><i class="fa fa-dashboard"></i> 报警统计报表</h1>
            <p> 报警统计饼图（产品类型、监控项、实例项），报警数量折线图</p>
        </div>
        {#            面包屑区域#}
        <ul class="app-breadcrumb breadcrumb side">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">仪表盘</li>
            <li class="breadcrumb-item active"><a href="#">报警-统计报表</a></li>
        </ul>
    </div>

    {#        报警统计报表#}
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                {#报警统计饼图#}
                <div class="row">
                    <div class="col-lg-5">
                        <div id="alarm_product_type_pie" style="min-height:300px;"></div>
                    </div>
                    <div class="col-lg-7">
                        <div id="alarm_metric_type_pie" style="min-height:300px;"></div>
                    </div>
                    <div class="col-lg-12">
                        <div id="alarm_instance_pie" style="min-height:300px;"></div>
                    </div>
                </div>
                <br><br>

                {# 报警数量折线图#}
                <div class="row">
                    <div class="col-lg-12">
                        <div id="alarm_line" style="min-height:300px;"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}


{% block custom_static %}

    {#    引用echarts#}
    <script src="https://cdn.bootcss.com/echarts/4.1.0/echarts.min.js"></script>

    <!-- Ajax Request-->
    <script type="text/javascript">
        {#csrf安全认证机制#}
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });

        {#产品类型ALARM饼图#}
        var myChart_ALARM_PRODUCT_TYPE_pie = echarts.init(document.getElementById('alarm_product_type_pie'));
        jQuery('#alarm_product_type_pie').showLoading();
        {#显示产品类型ALARM饼图#}
        $.ajax({
            type: "post",
            async: true,            //异步请求（同步请求将会锁住浏览器，用户其他操作必须等待请求完成才可以执行）
            url: "{% url 'dashboard:index_alarm_product_type_pie' %}",    //请求发送到TestServlet处
            dataType: "json",        //返回数据形式为json
            success: function (result) {
                var product_type_list = result['product_type_list']
                var product_type_alarm_list = result['product_type_alarm_list']
                var option = {
                    title: {
                        text: '产品类型报警比例',
                        subtext: '近30天',
                        x: 'center'
                    },
                    tooltip: {
                        trigger: 'item',
                        formatter: '{b}报警数:\n{c}'
                    },
                    legend: {
                        orient: 'vertical',
                        left: 'left',
                        data: product_type_list
                    },
                    series: [
                        {
                            name: '',
                            type: 'pie',
                            radius: '55%',
                            center: ['50%', '60%'],
                            data: product_type_alarm_list,
                            itemStyle: {
                                emphasis: {
                                    shadowBlur: 10,
                                    shadowOffsetX: 0,
                                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                                }
                            }
                        }
                    ]
                };
                myChart_ALARM_PRODUCT_TYPE_pie.setOption(option);
                jQuery('#alarm_product_type_pie').hideLoading();
            },
            error: function (errorMsg) {
                //请求失败时执行该函数
                jQuery('#alarm_product_type_pie').hideLoading();
            }
        });


        {#监控项类型ALARM饼图#}
        var myChart_ALARM_METRIC_TYPE_pie = echarts.init(document.getElementById('alarm_metric_type_pie'));
        jQuery('#alarm_metric_type_pie').showLoading();
        {#显示监控项类型ALARM饼图#}
        $.ajax({
            type: "post",
            async: true,            //异步请求（同步请求将会锁住浏览器，用户其他操作必须等待请求完成才可以执行）
            url: "{% url 'dashboard:index_alarm_metric_type_pie' %}",    //请求发送到TestServlet处
            dataType: "json",        //返回数据形式为json
            success: function (result) {
                var metric_type_list = result['metric_type_list']
                var metric_type_alarm_list = result['metric_type_alarm_list']
                var option = {
                    title: {
                        text: '监控项报警比例',
                        subtext: '近30天',
                        x: 'center'
                    },
                    tooltip: {
                        trigger: 'item',
                        formatter: '{b}报警数:\n{c}'
                    },
                    legend: {
                        orient: 'vertical',
                        left: 'left',
                        data: metric_type_list
                    },
                    series: [
                        {
                            name: '',
                            type: 'pie',
                            radius: '55%',
                            center: ['50%', '60%'],
                            data: metric_type_alarm_list,
                            itemStyle: {
                                emphasis: {
                                    shadowBlur: 10,
                                    shadowOffsetX: 0,
                                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                                }
                            }
                        }
                    ]
                };
                myChart_ALARM_METRIC_TYPE_pie.setOption(option);
                jQuery('#alarm_metric_type_pie').hideLoading();
            },
            error: function (errorMsg) {
                //请求失败时执行该函
                jQuery('#alarm_metric_type_pie').hideLoading();
            }
        });


        {#实例比例ALARM饼图#}
        var myChart_ALARM_INSTANCE_pie = echarts.init(document.getElementById('alarm_instance_pie'));
        jQuery('#alarm_instance_pie').showLoading();
        {#显示实例比例ALARM饼图#}
        $.ajax({
            type: "post",
            async: true,            //异步请求（同步请求将会锁住浏览器，用户其他操作必须等待请求完成才可以执行）
            url: "{% url 'dashboard:index_alarm_instance_pie' %}",    //请求发送到TestServlet处
            dataType: "json",        //返回数据形式为json
            success: function (result) {
                var instance_alarm_list = result['instance_alarm_list']
                var instance_list = result['instance_list']
                var option = {
                    title: {
                        text: '实例报警比例',
                        subtext: '近30天',
                        x: 'center'
                    },
                    tooltip: {
                        trigger: 'item',
                        formatter: '{b}报警数:\n{c}'
                    },
                    legend: {
                        orient: 'vertical',
                        left: 'left',
                        data: instance_list
                    },
                    series: [
                        {
                            name: '',
                            type: 'pie',
                            radius: '55%',
                            center: ['50%', '60%'],
                            data: instance_alarm_list,
                            itemStyle: {
                                emphasis: {
                                    shadowBlur: 10,
                                    shadowOffsetX: 0,
                                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                                }
                            }
                        }
                    ]
                };
                myChart_ALARM_INSTANCE_pie.setOption(option);
                jQuery('#alarm_instance_pie').hideLoading();
            },
            error: function (errorMsg) {
                //请求失败时执行该函
                jQuery('#alarm_instance_pie').hideLoading();
            }
        });


        {#ALARM - line图#}
        var myChart_ALARM_line = echarts.init(document.getElementById('alarm_line'));
        {#显示loading加载样式#}
        jQuery('#alarm_line').showLoading();
        {#显示RDS - CPU - line图。#}
        $.ajax({
            type: "post",
            async: true,            //异步请求（同步请求将会锁住浏览器，用户其他操作必须等待请求完成才可以执行）
            url: "{% url 'dashboard:index_alarm_line' %}",    //请求发送到TestServlet处
            dataType: "json",        //返回数据形式为json
            success: function (result) {
                var alarm_num_x = result['alarm_num_x'];
                var alarm_num_y = result['alarm_num_y'];
                var option = {
                    title: {
                        text: '报警数量趋势（单位：次）',
                        subtext: '今年内'
                    },
                    tooltip: {
                        trigger: 'axis',
                        axisPointer: {
                            type: 'cross',
                            label: {
                                backgroundColor: '#6a7985'
                            }
                        },
                        formatter: '{b}月份报警数量:\n{c}次'
                    },
                    legend: {
                        data: ['报警数量趋势（单位：次）']
                    },
                    toolbox: {
                        feature: {
                            saveAsImage: {},
                            magicType: {
                                type: ['line', 'bar']
                            }
                        }
                    },
                    grid: {
                        left: '3%',
                        right: '4%',
                        bottom: '3%',
                        containLabel: true
                    },
                    xAxis: [
                        {
                            type: 'category',
                            boundaryGap: false,
                            data: alarm_num_x,
                            axisLabel: {
                                interval: 'auto',
                            }
                        }
                    ],
                    yAxis: [
                        {
                            type: 'value',
                            axisLabel: {
                                show: true,
                                interval: 'auto',
                                formatter: '{value}'
                            },
                            show: true
                        }
                    ],
                    series: [{
                        data: alarm_num_y,
                        type: 'bar',
                        itemStyle: {
                            normal: {
                                color: '#0099cc',  //圈圈的颜色
                                lineStyle: {
                                    color: '#0099cc'  //线的颜色
                                }
                            }
                        },
                        areaStyle: {}
                    }]
                };
                myChart_ALARM_line.setOption(option);
                jQuery('#alarm_line').hideLoading();
            },
            error: function (errorMsg) {
                //请求失败时执行该函
                jQuery('#alarm_line').hideLoading();
            }
        });


    </script>

{% endblock %}